<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>Log4jView</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.info.log4jview</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Installer log</string>
			<key>match</key>
			<string>^(\d{4}\/\d{2}\/\d{2} \d{2}\:\d{2}\:\d{2}) \- (.*)$</string>
			<key>name</key>
			<string>string.quoted.log4jview</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.error.log4jview</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>exception jboss</string>
			<key>match</key>
			<string>^([a-zA-Z\s]*)(.*Exception\:)(\s*.*)$</string>
			<key>name</key>
			<string>string.quoted.log4jview</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.warn.log4jview</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.warn.message.log4jview</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>stacktrace jboss</string>
			<key>match</key>
			<string>^(\s*)(at )(.*)(\(.*\))$</string>
			<key>name</key>
			<string>string.quoted.log4jview</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.warn.log4jview</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.warn.log4jview</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.warn.message.log4jview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>warn jboss</string>
			<key>match</key>
			<string>^(.*)(WARN)\s*(\[.*\])\s*(.*)$</string>
			<key>name</key>
			<string>string.quoted.log4jview</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.info.log4jview</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.info.log4jview</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.info.message.log4jview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>info jboss</string>
			<key>match</key>
			<string>^(.*)(INFO)\s*(\[.*\])\s*(.*)$</string>
			<key>name</key>
			<string>string.quoted.log4jview</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.error.log4jview</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.error.log4jview</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.error.message.log4jview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>error jboss</string>
			<key>match</key>
			<string>^(.*)(ERROR)\s*(\[.*\])\s*(.*)$</string>
			<key>name</key>
			<string>string.quoted.log4jview</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.debug.log4jview</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.debug.log4jview</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.debug.message.log4jview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>debug jboss</string>
			<key>match</key>
			<string>^(.*)(DEBUG)\s*(\[.*\])\s*(.*)$</string>
			<key>name</key>
			<string>string.quoted.log4jview</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.trace.log4jview</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.trace.log4jview</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.trace.message.log4jview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>trace jboss</string>
			<key>match</key>
			<string>^(.*)(TRACE)\s*(\[.*\])\s*(.*)$</string>
			<key>name</key>
			<string>string.quoted.log4jview</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4jview</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.log4jview</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.log4jview</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.message.log4jview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>fatal jboss</string>
			<key>match</key>
			<string>^(.*)(FATAL)\s*(\[.*\])\s*(.*)$</string>
			<key>name</key>
			<string>string.quoted.log4jview</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.log4jview</string>
	<key>uuid</key>
	<string>59d2eab0-506c-4c33-8e2f-a6a74820383b</string>
</dict>
</plist>
